export enum SandboxErrorCode {
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
  MODULE_NOT_FOUND = 'MODULE_NOT_FOUND',
  ANALYSIS_NOT_FOUND = 'ANALYSIS_NOT_FOUND',
  INVALID_STATE_TRANSITION = 'INVALID_STATE_TRANSITION',
  DUPLICATE_SESSION = 'DUPLICATE_SESSION',
  MAX_ACTIVE_SANDBOXES = 'MAX_ACTIVE_SANDBOXES',
  UNSUPPORTED_STACK = 'UNSUPPORTED_STACK',
  EXTENSION_POLICY_VIOLATION = 'EXTENSION_POLICY_VIOLATION',
  ORCHESTRATION_FAILURE = 'ORCHESTRATION_FAILURE',
}

export const MAX_ACTIVE_SANDBOXES_PER_USER = 3;
export const DEFAULT_TTL_HOURS = 4;
export const MAX_TTL_HOURS = 8;
export const MIN_EXTENSION_HOURS = 1;
export const MAX_EXTENSION_HOURS = 4;
